---
title: "Readme"
author: "Haoyi Wei"
date: "2022-12-21"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Course 2: R Programming
# Programming Assignment 1: Air Pollution
This repository is a Haoyi Wei submission for R Programming course project. It contains coding manipulating air pollution data. It created three functions to answer questions in quiz 1.

## Files
DS2_HW1.html: A file documented all the questions and answers.
DS2_HW1.pdf: A file documented all the questions and answers.

# Programming Assignment 2: Lexical Scoping
This repository is a Haoyi Wei submission for R Programming course project. It contains coding utilizing lexical Scoping.

## Files
DS2_HW2.html: A file documented all the questions and answers.
DS2_HW2.pdf: A file documented all the questions and answers.

# Programming Assignment 3: Hospital Quality
This repository is a Haoyi Wei submission for R Programming course project. It contains coding utilizing lexical Scoping.

## Files
DS2_HW3.html: A file documented all the questions and answers.


